name: CI

on:
  push:
    branches:
      - master
  pull_request: ~

env:
  # Increment this to invalidate the cache without modifying requirements.txt
  PIPCACHEVERSION: 0
  PYTHONVERSION: '3.9.x'  # qutip does not support 3.10 yet

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHONVERSION }}
      - name: Set up cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ env.PIPCACHEVERSION }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install package and pylint
        run: python -m pip install . pylint
      - name: Run pylint
        run: pylint --errors-only --jobs=0 pyEPR

  test_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHONVERSION }}
      - name: Set up cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ env.PIPCACHEVERSION }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
      - name: Install package and sphinx
        run: python -m pip install . Sphinx
      - name: Make docs
        run: |
          cd docs
          make html
      - name: Upload docs to artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: docs
          path: docs/build/html/
          retention-days: 5