name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '👏👏👏 You are awesome! Thank you for making your first issue to pyEPR '' first issue'
        pr-message: '👏👏👏 You are awesome! Thank you for making your first pull request to pyEPR! This team work makes the pyEPR dream work! '' first pr'
